server:
  port: 8080
  #servlet:
    #context-path: /health-sys/api/v1
spring:
  application:
    name: HealthSys-API
  profiles:
    active: dev
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
logging:
  level:
    org.springframework.security: DEBUG
